### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bobhenl** [heyxmirko/HubPvP#1]
`
0:43:40] [Server thread/INFO]: JustaRandomGuy lost connection: Disconnected
[20:43:40] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to HubPvP v1.5.5
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "me.quared.hubpvp.util.adapters.ItemMetaAdapter.serialize(org.bukkit.inventory.ItemStack)" is null
    at me.quared.hubpvp.util.ArmorSerializationUtil.serializeArmorArray(ArmorSerializationUtil.java:17) ~[HubPvP-1.5.5.jar:?]
    at me.quared.hubpvp.managers.DatabaseManager.saveOldPlayerData(DatabaseManager.java:20) ~[HubPvP-1.5.5.jar:?]
    at me.quared.hubpvp.listeners.PlayerJoinListener.onQuit(PlayerJoinListener.java:62) ~[HubPvP-1.5.5.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2369.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2165]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:615) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:599) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2164) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2144) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131) ~[?:?]
    at net.minecraft.network.Connection.handleDisconnection(Connection.java:846) ~[?:?]
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1781) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2165]
    at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

**Comment by heyxmirko** [comment]
Fixed
